FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /lumastic
WORKDIR /lumastic

COPY Gemfile /lumastic/Gemfile
COPY Gemfile.lock /lumastic/Gemfile.lock

RUN bundle install --without development test

ENV RAILS_ENV production
ENV RACK_ENV production

COPY . /lumastic

EXPOSE 3000

CMD ['rails', 'server', '-b', '0.0.0.0']