FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /lumastic
WORKDIR /lumastic

COPY Gemfile /lumastic/Gemfile
COPY Gemfile.lock /lumastic/Gemfile.lock

RUN bundle install

#ENV RAILS_ENV production
#ENV RACK_ENV production

EXPOSE 3000
EXPOSE 80

COPY . /lumastic



