FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
WORKDIR /lumastic
ADD Gemfile Gemfile.lock /lumastic/
RUN bundle install --without development test
ADD . .
ENV RAILS_ENV=production
ARG secret_key_base
ENV SECRET_KEY_BASE=$secret_key_base
RUN bundle exec rails assets:precompile
CMD rails server -b '0.0.0.0'
