FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
WORKDIR /lumastic
ADD Gemfile Gemfile.lock /lumastic/
RUN bundle install --without development test
ADD . .
RUN RAILS_ENV=production bundle exec rake assets:precompile
CMD bundle exec rails server -b '0.0.0.0'
