FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
WORKDIR /lumastic
ADD Gemfile Gemfile.lock /lumastic/
RUN bundle install --without development test
ADD . .
CMD RAILS_ENV=production rails assets:precompile && rails server -b '0.0.0.0'
